"""empty message

Revision ID: 49353c4fa2cc
Revises: 73aac7ddaa59
Create Date: 2020-05-21 10:09:34.106353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49353c4fa2cc'
down_revision = '73aac7ddaa59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
